### ISSUE TITLE
deserialize_lpcm can't be used to load batches from IO

### ISSUE THREAD

**Issue by SimonDanisch** [beacon-biosignals/Onda.jl#40]
MWE: 
```julia
using Onda
# Use OndaViz to create a dataset... Or just use any dataset you have
using OndaViz
# run from examples folder (viewer.jl)
include("../scripts/data_generation.jl")
dataset_path = joinpath(@__DIR__, "test.onda")
create_big_test_dataset(dataset_path, 1, 500)
dataset = Dataset(dataset_path)
### setup IO & serializers
uuid, rec = first(dataset.recordings)
signal = rec.signals[:eeg]
path = samples_path(dataset, uuid, :eeg, signal.file_extension)
serializer = Onda.serializer(signal)
io = open(path, "r")
# load from stream directly. Works on first:
Onda.deserialize_lpcm(io, serializer, 0, 100)
# Second time: zstd error:
Onda.deserialize_lpcm(io, serializer, 0, 100)
```

**Comment by jrevels** [comment]
I started diving into this a bit while writing tests for #47 (which is otherwise pretty unrelated). The underlying issue here is that you can't really do the following (and our implementation currently induces this under the hood):

```
julia> dbytes = rand(UInt8, 100);

julia> cbytes = transcode(ZstdCompressor, dbytes);

julia> io = IOBuffer(cbytes);

julia> str = ZstdDecompressorStream(io);

julia> read(str, 10) == dbytes[1:10]
true

julia> read(ZstdDecompressorStream(io), 1) # hangs
```

Seems like zstd uses a stateful decompression context under the hood, so that might mean we can't just allocate a new context and "pick up where we left off" in the underlying stream (ref "Buffer-less streaming decompression" here https://facebook.github.io/zstd/zstd_manual.html#Chapter28). This makes sense; otherwise, how would we keep track of whether we're basically in the middle of a compressed block or not for these "partial block reads" mid-stream?

I think we'll need to tweak Onda's streaming (de)serialization API to allow for situations like these with block-based codecs. There's a couple of easy options here AFAICT, I'll start thinking about the tradeoffs...
