### ISSUE TITLE
annotate! conflict with Plots.annotate!

### ISSUE THREAD

**Issue by swhustla** [beacon-biosignals/Onda.jl#48]
Hi, fairly new to Julia so maybe this isn't a big deal.   
However if I try `using Plots` after `using Onda`, I get this warning:  
`WARNING: using Plots.annotate! in module Main conflicts with an existing identifier.
`

**Comment by ararslan** [comment]
Yep, that's a thing that happens sometimes; since neither package depends on the other and Julia doesn't have method merging, they don't share the same namespace. That means that loading both packages gives you two `annotate!`s. Julia won't know which one you meant when you go to call it, so the warning is telling you that you'll need to qualify calls with the module name whenever you call `annotate!`. So for example, to add an `Annotation` to a `Recording` in the same module in which you've loaded Plots, you'll need to write `Onda.annotate!`. Similarly, to annotate a plot in the same module in which you've loaded Onda, you'll need to write `Plots.annotate!`. If you annotate neither recordings nor plots in your module, you can safely ignore the warning.

Note that this behavior is different from languages like R, where an identifier will shadow another (also with a warning), so e.g. `annotate!` would mean `Plots.annotate!` if you load Onda then Plots, or `Onda.annotate!` if you loaded Plots then Onda. Julia instead opts to make the order in which packages are loaded insignificant (or as much so as possible).

**Comment by jrevels** [comment]
Hi @swhustla, thanks for the issue! Like @ararslan mentioned, the behavior mentioned in the OP is normal Julia namespacing behavior, so I'm going to close this particular issue. But thanks for checking out the package, and let us know if you run into any other snags!

**Comment by swhustla** [comment]
Thanks for the explanations and tips on annotation of `Plots`, appreciated.
